### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by s7726** [dtuma/processdash#3]
http://enable-cors.org/
http://www.html5rocks.com/en/tutorials/cors/

Enable CORS support to allow scraping from other applications.

`Access-Control-Allow-Origin: *`

**Comment by dtuma** [comment]
It seems to me that open, unrestricted access for all CORS requests could be a security hole.

Consider this: all personal dashboards run on http://localhost:2468/ by default, and all team dashboards run on http://localhost:3000/.  If CORS support was enabled with the "*" qualifier as you suggest, what would prevent a malicious attacker from silently stealing sensitive data about your organization's projects? All they would have to do is create a website on the public Internet that makes CORS requests to http://localhost:3000/, then trick you into visiting their site.

If I'm misunderstanding the CORS security model, feel free to educate me.

Further, shouldn't it be possible for you to selectively enable CORS by writing your own JSPs? The dashboard can run custom reports that you write and bundle into WAR files. Couldn't you write a JSP which:
1. produces a set of data you wish to consume (possibly making use of a jsp:include tag, or possibly by running your own HQL queries and generating custom content)
2. adds the "Access-Control-Allow-Origin: *" header to the response

Your external application would then make a CORS request to something like http://localhost:3000/your/jsp/page

Once again, if I'm misunderstanding the mechanism for CORS, feel free to educate me. I admit I'm not as fluent in CORS as I could be.
